# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake Build test

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake --preset vs2022-x64

    - name: Build (Debug)
      if: env.BUILD_TYPE == 'Debug'
      run: cmake --build --preset build-debug

    - name: Build (Release)
      if: env.BUILD_TYPE != 'Debug'
      run: cmake --build --preset build-release
